# TCL File Generated by Component Editor 18.1
# Wed Mar 05 10:38:33 GMT 2025
# DO NOT MODIFY


# 
# Accelerometer_filter "Accelerometer_filter" v1.0
# Leo Sawatyanon 2025.03.05.10:38:33
# SPI & Filter module for Accelerometer data
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Accelerometer_filter
# 
set_module_property DESCRIPTION "SPI & Filter module for Accelerometer data"
set_module_property NAME Accelerometer_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Leo Sawatyanon"
set_module_property DISPLAY_NAME Accelerometer_filter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL accel_peripheral
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accelerometer_avalon.v VERILOG PATH accelerometer_avalon.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL accel_peripheral
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accelerometer_avalon.v VERILOG PATH accelerometer_avalon.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Accel_x
# 
add_interface Accel_x conduit end
set_interface_property Accel_x associatedClock clock
set_interface_property Accel_x associatedReset ""
set_interface_property Accel_x ENABLED true
set_interface_property Accel_x EXPORT_OF ""
set_interface_property Accel_x PORT_NAME_MAP ""
set_interface_property Accel_x CMSIS_SVD_VARIABLES ""
set_interface_property Accel_x SVD_ADDRESS_GROUP ""

add_interface_port Accel_x accel_x writebyteenable_n Input 16


# 
# connection point Accel_y
# 
add_interface Accel_y conduit end
set_interface_property Accel_y associatedClock clock
set_interface_property Accel_y associatedReset ""
set_interface_property Accel_y ENABLED true
set_interface_property Accel_y EXPORT_OF ""
set_interface_property Accel_y PORT_NAME_MAP ""
set_interface_property Accel_y CMSIS_SVD_VARIABLES ""
set_interface_property Accel_y SVD_ADDRESS_GROUP ""

add_interface_port Accel_y accel_y writebyteenable_n Input 16


# 
# connection point Accel_z
# 
add_interface Accel_z conduit end
set_interface_property Accel_z associatedClock clock
set_interface_property Accel_z associatedReset ""
set_interface_property Accel_z ENABLED true
set_interface_property Accel_z EXPORT_OF ""
set_interface_property Accel_z PORT_NAME_MAP ""
set_interface_property Accel_z CMSIS_SVD_VARIABLES ""
set_interface_property Accel_z SVD_ADDRESS_GROUP ""

add_interface_port Accel_z accel_z writebyteenable_n Input 16

